logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    io.subbu.estore: INFO

spring:
  datasource:
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "subbu"
    password: "pa55ward"
    driver-class-name: "org.h2.Driver"
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  service:
    url:
      product: "http://localhost:8082/api/products/"
      user: "http://localhost:8083/api/usres"
